version: "3.8"
services:
  api:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/memoryapi
    environment:
      FLASK_ENV: development
    depends_on:
      - database

  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: postgres
      POSTGRES_DB: archie_memory

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  